# generated by datamodel-codegen:
#   filename:  http://localhost:3000/api/spec.json
#   timestamp: 2026-07-20T14:33:38+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import AwareDatetime, BaseModel, Field, RootModel, constr


class Type(Enum):
    human = 'human'
    ai = 'ai'


class Message(BaseModel):
    type: Type
    content: str
    name: constr(min_length=1) | None = None
    additionalKwargs: (
        dict[
            str,
            str
            | float
            | bool
            | list[str | float | bool | list[Any] | dict[str, Any] | None]
            | dict[str, str | float | bool | list[Any] | dict[str, Any] | None]
            | None,
        ]
        | None
    ) = None
    responseMetadata: (
        dict[
            str,
            str
            | float
            | bool
            | list[str | float | bool | list[Any] | dict[str, Any] | None]
            | dict[str, str | float | bool | list[Any] | dict[str, Any] | None]
            | None,
        ]
        | None
    ) = None
    toolCalls: (
        list[
            str
            | float
            | bool
            | list[str | float | bool | list[Any] | dict[str, Any] | None]
            | dict[str, str | float | bool | list[Any] | dict[str, Any] | None]
            | None
        ]
        | None
    ) = None
    invalidToolCalls: (
        list[
            str
            | float
            | bool
            | list[str | float | bool | list[Any] | dict[str, Any] | None]
            | dict[str, str | float | bool | list[Any] | dict[str, Any] | None]
            | None
        ]
        | None
    ) = None


class AllowedDecision(Enum):
    approve = 'approve'
    edit = 'edit'
    reject = 'reject'
    respond = 'respond'


class ActionRequest(BaseModel):
    name: constr(min_length=1, max_length=100)
    description: constr(min_length=1, max_length=2000) | None = None
    args: (
        dict[
            str,
            str
            | float
            | bool
            | list[str | float | bool | list[Any] | dict[str, Any] | None]
            | dict[str, str | float | bool | list[Any] | dict[str, Any] | None]
            | None,
        ]
        | None
    ) = None
    allowedDecisions: list[AllowedDecision] | None = None
    argsSchema: (
        dict[
            str,
            str
            | float
            | bool
            | list[str | float | bool | list[Any] | dict[str, Any] | None]
            | dict[str, str | float | bool | list[Any] | dict[str, Any] | None]
            | None,
        ]
        | None
    ) = None


class InterruptsPostRequest(BaseModel):
    title: constr(min_length=2, max_length=100)
    description: constr(min_length=2, max_length=2000)
    classificationId: constr(min_length=1)
    externalId: constr(min_length=1) | None = None
    messages: list[Message] | None = Field(None, max_length=200)
    actionRequests: list[ActionRequest] | None = Field(None, max_length=50)


class Priority(Enum):
    LOW = 'LOW'
    MEDIUM = 'MEDIUM'
    HIGH = 'HIGH'


class Color(Enum):
    red = 'red'
    orange = 'orange'
    amber = 'amber'
    yellow = 'yellow'
    lime = 'lime'
    green = 'green'
    emerald = 'emerald'
    teal = 'teal'
    cyan = 'cyan'
    sky = 'sky'
    blue = 'blue'
    indigo = 'indigo'
    violet = 'violet'
    purple = 'purple'
    fuchsia = 'fuchsia'
    pink = 'pink'
    rose = 'rose'
    zinc = 'zinc'


class Classification(BaseModel):
    id: str
    createdAt: AwareDatetime
    updatedAt: AwareDatetime
    organizationId: str
    name: str
    description: str
    priority: Priority
    color: Color


class Message1(BaseModel):
    id: str
    createdAt: AwareDatetime
    interruptId: str | None
    type: Type
    content: str
    name: str | None
    additionalKwargs: Any | None = None
    responseMetadata: Any | None = None
    toolCalls: Any | None = None
    invalidToolCalls: Any | None = None


class ActionRequest1(BaseModel):
    id: str
    createdAt: AwareDatetime
    interruptId: str
    name: str
    args: Any | None = None
    description: str | None
    allowedDecisions: list[AllowedDecision]
    argsSchema: Any | None = None


class InterruptsPostResponse(BaseModel):
    id: str
    timeOpened: AwareDatetime
    createdAt: AwareDatetime
    updatedAt: AwareDatetime
    organizationId: str
    externalId: str | None
    title: str
    answered: bool
    description: str
    classificationId: str
    classification: Classification
    messages: list[Message1]
    actionRequests: list[ActionRequest1]


class Data(BaseModel):
    message: str


class InterruptsPostResponse2(BaseModel):
    defined: Literal[True]
    code: Literal['ORGANIZATION_ALREADY_EXISTS']
    status: Literal[500]
    message: str
    data: Data


class InterruptsPostResponse3(BaseModel):
    defined: Literal[False]
    code: str
    status: float
    message: str
    data: Any | None = None


class InterruptsPostResponse1(
    RootModel[InterruptsPostResponse2 | InterruptsPostResponse3]
):
    root: InterruptsPostResponse2 | InterruptsPostResponse3


class Classification1(BaseModel):
    id: str
    createdAt: AwareDatetime
    updatedAt: AwareDatetime
    organizationId: str
    name: str
    description: str
    priority: Priority
    color: Color


class Message2(BaseModel):
    id: str
    createdAt: AwareDatetime
    interruptId: str | None
    type: Type
    content: str
    name: str | None
    additionalKwargs: Any | None = None
    responseMetadata: Any | None = None
    toolCalls: Any | None = None
    invalidToolCalls: Any | None = None


class ActionRequest2(BaseModel):
    id: str
    createdAt: AwareDatetime
    interruptId: str
    name: str
    args: Any | None = None
    description: str | None
    allowedDecisions: list[AllowedDecision]
    argsSchema: Any | None = None


class InterruptsGetResponseItem(BaseModel):
    id: str
    timeOpened: AwareDatetime
    createdAt: AwareDatetime
    updatedAt: AwareDatetime
    organizationId: str
    externalId: str | None
    title: str
    answered: bool
    description: str
    classificationId: str
    classification: Classification1
    messages: list[Message2]
    actionRequests: list[ActionRequest2]


class InterruptsGetResponse(RootModel[list[InterruptsGetResponseItem]]):
    root: list[InterruptsGetResponseItem]


class InterruptsGetResponse2(BaseModel):
    defined: Literal[True]
    code: Literal['ORGANIZATION_ALREADY_EXISTS']
    status: Literal[500]
    message: str
    data: Data


class InterruptsGetResponse3(BaseModel):
    defined: Literal[False]
    code: str
    status: float
    message: str
    data: Any | None = None


class InterruptsGetResponse1(
    RootModel[InterruptsGetResponse2 | InterruptsGetResponse3]
):
    root: InterruptsGetResponse2 | InterruptsGetResponse3
