# generated by datamodel-codegen:
#   filename:  http://localhost:3000/api/spec.json
#   timestamp: 2026-08-11T12:47:08+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import AwareDatetime, BaseModel, Field, RootModel, constr


class Type(Enum):
    human = 'human'
    ai = 'ai'


class Message(BaseModel):
    type: Type
    content: str
    name: constr(min_length=1) | None = None
    additionalKwargs: (
        dict[
            str,
            str
            | float
            | bool
            | list[str | float | bool | list[Any] | dict[str, Any] | None]
            | dict[str, str | float | bool | list[Any] | dict[str, Any] | None]
            | None,
        ]
        | None
    ) = None
    responseMetadata: (
        dict[
            str,
            str
            | float
            | bool
            | list[str | float | bool | list[Any] | dict[str, Any] | None]
            | dict[str, str | float | bool | list[Any] | dict[str, Any] | None]
            | None,
        ]
        | None
    ) = None
    toolCalls: (
        list[
            str
            | float
            | bool
            | list[str | float | bool | list[Any] | dict[str, Any] | None]
            | dict[str, str | float | bool | list[Any] | dict[str, Any] | None]
            | None
        ]
        | None
    ) = None
    invalidToolCalls: (
        list[
            str
            | float
            | bool
            | list[str | float | bool | list[Any] | dict[str, Any] | None]
            | dict[str, str | float | bool | list[Any] | dict[str, Any] | None]
            | None
        ]
        | None
    ) = None


class AllowedDecision(Enum):
    approve = 'approve'
    edit = 'edit'
    reject = 'reject'
    respond = 'respond'


class ActionRequest(BaseModel):
    name: constr(min_length=1, max_length=100)
    description: constr(min_length=1, max_length=2000) | None = None
    args: (
        dict[
            str,
            str
            | float
            | bool
            | list[str | float | bool | list[Any] | dict[str, Any] | None]
            | dict[str, str | float | bool | list[Any] | dict[str, Any] | None]
            | None,
        ]
        | None
    ) = None
    allowedDecisions: list[AllowedDecision] = Field(..., min_length=1)
    argsSchema: (
        dict[
            str,
            str
            | float
            | bool
            | list[str | float | bool | list[Any] | dict[str, Any] | None]
            | dict[str, str | float | bool | list[Any] | dict[str, Any] | None]
            | None,
        ]
        | None
    ) = None


class InterruptsPostRequest(BaseModel):
    title: constr(min_length=2, max_length=100)
    description: constr(min_length=2, max_length=2000)
    classificationId: constr(min_length=1) | None = None
    externalId: constr(min_length=1) | None = None
    messages: list[Message] | None = Field(None, max_length=200)
    actionRequests: list[ActionRequest] = Field(..., max_length=50, min_length=1)


class Assignee(BaseModel):
    id: str
    name: str
    email: str
    image: str | None


class Priority(Enum):
    LOW = 'LOW'
    MEDIUM = 'MEDIUM'
    HIGH = 'HIGH'


class Color(Enum):
    red = 'red'
    orange = 'orange'
    amber = 'amber'
    yellow = 'yellow'
    lime = 'lime'
    green = 'green'
    emerald = 'emerald'
    teal = 'teal'
    cyan = 'cyan'
    sky = 'sky'
    blue = 'blue'
    indigo = 'indigo'
    violet = 'violet'
    purple = 'purple'
    fuchsia = 'fuchsia'
    pink = 'pink'
    rose = 'rose'
    zinc = 'zinc'


class Classification(BaseModel):
    id: str
    createdAt: AwareDatetime
    updatedAt: AwareDatetime
    organizationId: str
    name: str
    description: str
    priority: Priority
    color: Color


class ArgusSuggestedDecision(Enum):
    approve = 'approve'
    edit = 'edit'
    reject = 'reject'
    respond = 'respond'


class Message1(BaseModel):
    id: str
    createdAt: AwareDatetime
    interruptId: str | None
    type: Type
    content: str
    name: str | None
    additionalKwargs: Any | None = None
    responseMetadata: Any | None = None
    toolCalls: Any | None = None
    invalidToolCalls: Any | None = None


class Decision(Enum):
    approve = 'approve'
    edit = 'edit'
    reject = 'reject'
    respond = 'respond'


class ActionRequest1(BaseModel):
    id: str
    createdAt: AwareDatetime
    interruptId: str
    name: str
    args: Any | None = None
    description: str | None
    allowedDecisions: list[AllowedDecision]
    argsSchema: Any | None = None
    decision: Decision | None
    editedArgs: Any | None = None
    responseText: str | None
    decidedAt: AwareDatetime | None
    decidedByName: str | None


class Type2(Enum):
    assigned = 'assigned'
    unassigned = 'unassigned'
    classified = 'classified'
    escalated = 'escalated'
    decided = 'decided'


class ClassificationColor(Enum):
    red = 'red'
    orange = 'orange'
    amber = 'amber'
    yellow = 'yellow'
    lime = 'lime'
    green = 'green'
    emerald = 'emerald'
    teal = 'teal'
    cyan = 'cyan'
    sky = 'sky'
    blue = 'blue'
    indigo = 'indigo'
    violet = 'violet'
    purple = 'purple'
    fuchsia = 'fuchsia'
    pink = 'pink'
    rose = 'rose'
    zinc = 'zinc'


class AuditEvent(BaseModel):
    id: str
    createdAt: AwareDatetime
    interruptId: str
    type: Type2
    actorName: str | None
    assigneeName: str | None
    classificationName: str | None
    classificationColor: ClassificationColor | None
    decision: Decision | None
    actionName: str | None


class InterruptsPostResponse(BaseModel):
    id: str
    timeOpened: AwareDatetime
    createdAt: AwareDatetime
    updatedAt: AwareDatetime
    organizationId: str
    externalId: str | None
    title: str
    answered: bool
    answeredAt: AwareDatetime | None
    description: str
    escalated: bool
    assigneeId: str | None
    assignee: Assignee | None
    classificationId: str | None
    classification: Classification | None
    argusSummary: str | None
    argusSuggestedDecision: ArgusSuggestedDecision | None
    argusSuggestedResponse: str | None
    messages: list[Message1]
    actionRequests: list[ActionRequest1]
    auditEvents: list[AuditEvent]


class Data(BaseModel):
    featureId: str
    message: str


class InterruptsPostResponse2(BaseModel):
    defined: Literal[True]
    code: Literal['USAGE_LIMIT_REACHED']
    status: Literal[402]
    message: str
    data: Data


class Data1(BaseModel):
    featureId: str | None = None
    message: str


class InterruptsPostResponse3(BaseModel):
    defined: Literal[True]
    code: Literal['PLAN_REQUIRED']
    status: Literal[402]
    message: str
    data: Data1


class InterruptsPostResponse4(BaseModel):
    defined: Literal[True]
    code: Literal['ADDON_REQUIRED']
    status: Literal[402]
    message: str
    data: Data1


class InterruptsPostResponse5(BaseModel):
    defined: Literal[False]
    code: str
    status: float
    message: str
    data: Any | None = None


class InterruptsPostResponse1(
    RootModel[
        InterruptsPostResponse2
        | InterruptsPostResponse3
        | InterruptsPostResponse4
        | InterruptsPostResponse5
    ]
):
    root: (
        InterruptsPostResponse2
        | InterruptsPostResponse3
        | InterruptsPostResponse4
        | InterruptsPostResponse5
    )


class Data3(BaseModel):
    message: str


class InterruptsPostResponse7(BaseModel):
    defined: Literal[True]
    code: Literal['WORKSPACE_LIMIT_REACHED']
    status: Literal[403]
    message: str
    data: Data3


class InterruptsPostResponse8(BaseModel):
    defined: Literal[False]
    code: str
    status: float
    message: str
    data: Any | None = None


class InterruptsPostResponse6(
    RootModel[InterruptsPostResponse7 | InterruptsPostResponse8]
):
    root: InterruptsPostResponse7 | InterruptsPostResponse8


class InterruptsPostResponse10(BaseModel):
    defined: Literal[True]
    code: Literal['ORGANIZATION_ALREADY_EXISTS']
    status: Literal[500]
    message: str
    data: Data3


class InterruptsPostResponse11(BaseModel):
    defined: Literal[False]
    code: str
    status: float
    message: str
    data: Any | None = None


class InterruptsPostResponse9(
    RootModel[InterruptsPostResponse10 | InterruptsPostResponse11]
):
    root: InterruptsPostResponse10 | InterruptsPostResponse11


class Classification1(BaseModel):
    id: str
    createdAt: AwareDatetime
    updatedAt: AwareDatetime
    organizationId: str
    name: str
    description: str
    priority: Priority
    color: Color


class Type3(Enum):
    human = 'human'
    ai = 'ai'


class Message2(BaseModel):
    id: str
    createdAt: AwareDatetime
    interruptId: str | None
    type: Type3
    content: str
    name: str | None
    additionalKwargs: Any | None = None
    responseMetadata: Any | None = None
    toolCalls: Any | None = None
    invalidToolCalls: Any | None = None


class ActionRequest2(BaseModel):
    id: str
    createdAt: AwareDatetime
    interruptId: str
    name: str
    args: Any | None = None
    description: str | None
    allowedDecisions: list[AllowedDecision]
    argsSchema: Any | None = None
    decision: Decision | None
    editedArgs: Any | None = None
    responseText: str | None
    decidedAt: AwareDatetime | None
    decidedByName: str | None


class Type4(Enum):
    assigned = 'assigned'
    unassigned = 'unassigned'
    classified = 'classified'
    escalated = 'escalated'
    decided = 'decided'


class AuditEvent1(BaseModel):
    id: str
    createdAt: AwareDatetime
    interruptId: str
    type: Type4
    actorName: str | None
    assigneeName: str | None
    classificationName: str | None
    classificationColor: ClassificationColor | None
    decision: Decision | None
    actionName: str | None


class InterruptsGetResponseItem(BaseModel):
    id: str
    timeOpened: AwareDatetime
    createdAt: AwareDatetime
    updatedAt: AwareDatetime
    organizationId: str
    externalId: str | None
    title: str
    answered: bool
    answeredAt: AwareDatetime | None
    description: str
    escalated: bool
    assigneeId: str | None
    assignee: Assignee | None
    classificationId: str | None
    classification: Classification1 | None
    argusSummary: str | None
    argusSuggestedDecision: ArgusSuggestedDecision | None
    argusSuggestedResponse: str | None
    messages: list[Message2]
    actionRequests: list[ActionRequest2]
    auditEvents: list[AuditEvent1]


class InterruptsGetResponse(RootModel[list[InterruptsGetResponseItem]]):
    root: list[InterruptsGetResponseItem]


class Data5(BaseModel):
    featureId: str
    message: str


class InterruptsGetResponse2(BaseModel):
    defined: Literal[True]
    code: Literal['USAGE_LIMIT_REACHED']
    status: Literal[402]
    message: str
    data: Data5


class Data6(BaseModel):
    featureId: str | None = None
    message: str


class InterruptsGetResponse3(BaseModel):
    defined: Literal[True]
    code: Literal['PLAN_REQUIRED']
    status: Literal[402]
    message: str
    data: Data6


class InterruptsGetResponse4(BaseModel):
    defined: Literal[True]
    code: Literal['ADDON_REQUIRED']
    status: Literal[402]
    message: str
    data: Data6


class InterruptsGetResponse5(BaseModel):
    defined: Literal[False]
    code: str
    status: float
    message: str
    data: Any | None = None


class InterruptsGetResponse1(
    RootModel[
        InterruptsGetResponse2
        | InterruptsGetResponse3
        | InterruptsGetResponse4
        | InterruptsGetResponse5
    ]
):
    root: (
        InterruptsGetResponse2
        | InterruptsGetResponse3
        | InterruptsGetResponse4
        | InterruptsGetResponse5
    )


class Data8(BaseModel):
    message: str


class InterruptsGetResponse7(BaseModel):
    defined: Literal[True]
    code: Literal['WORKSPACE_LIMIT_REACHED']
    status: Literal[403]
    message: str
    data: Data8


class InterruptsGetResponse8(BaseModel):
    defined: Literal[False]
    code: str
    status: float
    message: str
    data: Any | None = None


class InterruptsGetResponse6(
    RootModel[InterruptsGetResponse7 | InterruptsGetResponse8]
):
    root: InterruptsGetResponse7 | InterruptsGetResponse8


class InterruptsGetResponse10(BaseModel):
    defined: Literal[True]
    code: Literal['ORGANIZATION_ALREADY_EXISTS']
    status: Literal[500]
    message: str
    data: Data8


class InterruptsGetResponse11(BaseModel):
    defined: Literal[False]
    code: str
    status: float
    message: str
    data: Any | None = None


class InterruptsGetResponse9(
    RootModel[InterruptsGetResponse10 | InterruptsGetResponse11]
):
    root: InterruptsGetResponse10 | InterruptsGetResponse11


class Classification2(BaseModel):
    id: str
    createdAt: AwareDatetime
    updatedAt: AwareDatetime
    organizationId: str
    name: str
    description: str
    priority: Priority
    color: Color


class Type5(Enum):
    human = 'human'
    ai = 'ai'


class Message3(BaseModel):
    id: str
    createdAt: AwareDatetime
    interruptId: str | None
    type: Type5
    content: str
    name: str | None
    additionalKwargs: Any | None = None
    responseMetadata: Any | None = None
    toolCalls: Any | None = None
    invalidToolCalls: Any | None = None


class ActionRequest3(BaseModel):
    id: str
    createdAt: AwareDatetime
    interruptId: str
    name: str
    args: Any | None = None
    description: str | None
    allowedDecisions: list[AllowedDecision]
    argsSchema: Any | None = None
    decision: Decision | None
    editedArgs: Any | None = None
    responseText: str | None
    decidedAt: AwareDatetime | None
    decidedByName: str | None


class Type6(Enum):
    assigned = 'assigned'
    unassigned = 'unassigned'
    classified = 'classified'
    escalated = 'escalated'
    decided = 'decided'


class AuditEvent2(BaseModel):
    id: str
    createdAt: AwareDatetime
    interruptId: str
    type: Type6
    actorName: str | None
    assigneeName: str | None
    classificationName: str | None
    classificationColor: ClassificationColor | None
    decision: Decision | None
    actionName: str | None


class InterruptsIdGetResponse(BaseModel):
    id: str
    timeOpened: AwareDatetime
    createdAt: AwareDatetime
    updatedAt: AwareDatetime
    organizationId: str
    externalId: str | None
    title: str
    answered: bool
    answeredAt: AwareDatetime | None
    description: str
    escalated: bool
    assigneeId: str | None
    assignee: Assignee | None
    classificationId: str | None
    classification: Classification2 | None
    argusSummary: str | None
    argusSuggestedDecision: ArgusSuggestedDecision | None
    argusSuggestedResponse: str | None
    messages: list[Message3]
    actionRequests: list[ActionRequest3]
    auditEvents: list[AuditEvent2]


class Data10(BaseModel):
    featureId: str
    message: str


class InterruptsIdGetResponse2(BaseModel):
    defined: Literal[True]
    code: Literal['USAGE_LIMIT_REACHED']
    status: Literal[402]
    message: str
    data: Data10


class Data11(BaseModel):
    featureId: str | None = None
    message: str


class InterruptsIdGetResponse3(BaseModel):
    defined: Literal[True]
    code: Literal['PLAN_REQUIRED']
    status: Literal[402]
    message: str
    data: Data11


class InterruptsIdGetResponse4(BaseModel):
    defined: Literal[True]
    code: Literal['ADDON_REQUIRED']
    status: Literal[402]
    message: str
    data: Data11


class InterruptsIdGetResponse5(BaseModel):
    defined: Literal[False]
    code: str
    status: float
    message: str
    data: Any | None = None


class InterruptsIdGetResponse1(
    RootModel[
        InterruptsIdGetResponse2
        | InterruptsIdGetResponse3
        | InterruptsIdGetResponse4
        | InterruptsIdGetResponse5
    ]
):
    root: (
        InterruptsIdGetResponse2
        | InterruptsIdGetResponse3
        | InterruptsIdGetResponse4
        | InterruptsIdGetResponse5
    )


class Data13(BaseModel):
    message: str


class InterruptsIdGetResponse7(BaseModel):
    defined: Literal[True]
    code: Literal['WORKSPACE_LIMIT_REACHED']
    status: Literal[403]
    message: str
    data: Data13


class InterruptsIdGetResponse8(BaseModel):
    defined: Literal[False]
    code: str
    status: float
    message: str
    data: Any | None = None


class InterruptsIdGetResponse6(
    RootModel[InterruptsIdGetResponse7 | InterruptsIdGetResponse8]
):
    root: InterruptsIdGetResponse7 | InterruptsIdGetResponse8


class InterruptsIdGetResponse10(BaseModel):
    defined: Literal[True]
    code: Literal['ORGANIZATION_ALREADY_EXISTS']
    status: Literal[500]
    message: str
    data: Data13


class InterruptsIdGetResponse11(BaseModel):
    defined: Literal[False]
    code: str
    status: float
    message: str
    data: Any | None = None


class InterruptsIdGetResponse9(
    RootModel[InterruptsIdGetResponse10 | InterruptsIdGetResponse11]
):
    root: InterruptsIdGetResponse10 | InterruptsIdGetResponse11
